[programs.devnet]
myepicproject = "GjbwzGTZKtGJR2wjioBxYdSeL18wYBhaeSsVJfmsSAgn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/tevrat/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 